### ISSUE TITLE
Can't seem to get the following User-agent

### ISSUE THREAD

**Issue by redimongo** [opawg/user-agents-v2#3]
trying to get the device info for 
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36`
and also
`Overcast/1.0 Podcast Sync (+http://overcast.fm/)`
`Overcast/3.0 (+http://overcast.fm/; iOS podcast app)`

These are not registering.

**Comment by johnspurlock** [comment]
What are they?

**Comment by redimongo** [comment]
> What are they?


I know that 

Overcast/3.0 (+http://overcast.fm/; iOS podcast app)

Is iOS overcast application. 

And the other overcast/1.0 is there web spider.

**Comment by johnspurlock** [comment]
Can you try to be far more clear about what you are finding, and what you are expecting to see?  

For example, here's what I'm getting when testing those user agents against this `user-agents-v2` patterns repo:

```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
agent: {"type":"browser","name":"Chrome"}
device: {"type":"device","name":"Windows Computer","deviceType":"computer"}

Overcast/3.0 (+http://overcast.fm/; iOS podcast app)
agent: {"type":"app","name":"Overcast"}
device: {"type":"device","name":"Apple iPhone","deviceType":"mobile"}

Overcast/1.0 Podcast Sync (+http://overcast.fm/)
agent: {"type":"bot","name":"Overcast feed parser"}
```

Seems pretty correct to me

**Comment by redimongo** [comment]
> Can you try to be far more clear about what you are finding, and what you are expecting to see?
> 
> For example, here's what I'm getting when testing those user agents against this `user-agents-v2` patterns repo:
> 
> ```
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
> agent: {"type":"browser","name":"Chrome"}
> device: {"type":"device","name":"Windows Computer","deviceType":"computer"}
> 
> Overcast/3.0 (+http://overcast.fm/; iOS podcast app)
> agent: {"type":"app","name":"Overcast"}
> device: {"type":"device","name":"Apple iPhone","deviceType":"mobile"}
> 
> Overcast/1.0 Podcast Sync (+http://overcast.fm/)
> agent: {"type":"bot","name":"Overcast feed parser"}
> ```
> 
> Seems pretty correct to me

Sorry only saw this response today, do you by any chance have a sample of how you integrated the searching of these. Maybe I am missing a step or have it out of order?

**Comment by johnspurlock** [comment]
It depends on the language you're using, use the patterns in each entry to construct a regex to match against

the automated tests in this repo do this basic matching process in typescript/javascript to ensure each entry's examples match the associated pattern:
https://github.com/opawg/user-agents-v2/blob/master/.github/workflows/patterns_test.ts

starting at around line 98
