### ISSUE TITLE
Not valid json for apps.json file

### ISSUE THREAD

**Issue by majkiee** [opawg/user-agents-v2#31]
The following line does not pass json validation and parsing. It produces the following error `Invalid escape character in string`
https://github.com/opawg/user-agents-v2/blob/fb22360457a2bf8da6de59b0bf2941164bc854c0/src/apps.json#L1613

**Comment by jamescridland** [comment]
That's my fault entirely, sorry.

I have commit rights, but hoped I'd left pull requests for another contributor rather than simply push the requests through. I think I did push one request through in error. I've removed that line.

My apologies.

**Comment by majkiee** [comment]
it happens to the best of us, thanks for the quick fix 👍🏻

**Comment by majkiee** [comment]
@jamescridland one recommendation would be to put a github action in place to validate files on PR and commit to stop bad files from coming through. 
Example: https://github.com/marketplace/actions/json-yaml-validate

**Comment by jamescridland** [comment]
I'll let @johnspurlock make that decision. Thank you!

**Comment by johnspurlock** [comment]
This repo already has such a check - in this case the commit was pushed directly, not as a PR, where the check can stop a bad merge.

<img width="551" alt="image" src="https://github.com/opawg/user-agents-v2/assets/528937/ed77af74-6ced-482a-a01f-2efb271f5673">
